### ISSUE TITLE
prepare and publish web-ui to Zenodo so that it can be cited

### ISSUE THREAD

**Issue by jhpoelen** [osmose-model/osmose-web-api#185]
Now that we have a web ui #182 at https://github.com/osmose-model/osmose-model.github.io , we need a way to cite the work in our paper, as suggested by @agruss2 .

Suggested steps:

1. add a short description to the https://github.com/osmose-model/osmose-model.github.io repository. 
2. add a README.md with a description of what the web ui does and how it related to other projects like osmose-web-api and osmose-web-api-js . 
3. add a LICENSE file (just copy the one from osmose-web-api)
4. enable the Zenodo-GitHub integration 
5. create a release (see https://github.com/osmose-model/osmose-web-api/releases for template)
6. share the DOI with Arnaud so that the Web UI can be cited.

**Comment by QQ-Sortiz** [comment]
Hello @barriern,
CC: @agruss2 

I don't have enough access to edit the description for the osmose-web-ui. Can you help me with this? Thanks!

**Comment by FIN-casey** [comment]
Hello @jhpoelen,

Still unable to see the settings for editing the description and updating the Zenodo-Github integration. 

![image](https://user-images.githubusercontent.com/18322815/45491696-e20bb780-b79c-11e8-8804-2ce1f4cd261f.png)
![image](https://user-images.githubusercontent.com/18322815/45491712-efc13d00-b79c-11e8-8957-6a93e181bb9d.png)

**Comment by jhpoelen** [comment]
@QQ-Sortiz @FIN-casey @FIN-JBarile I just changed your permissions to "owner", instead of "write". I incorrectly assumed that "write" meant that you could change the settings of the repo also. Please let me know if things look better now.

**Comment by FIN-casey** [comment]
Hello @agruss2,
CC: @jhpoelen @FIN-JBarile 

Sharing with you the DOI for the osmose-model web ui. Thanks!

[![DOI](https://zenodo.org/badge/57102270.svg)](https://zenodo.org/badge/latestdoi/57102270)

**Comment by agruss2** [comment]
I think that the present issue has been fully addressed. I am, therefore, closing it. Many thanks for your great work everyone!
