### ISSUE TITLE
prepare and publish fishbase/sealifebase archives so that they can be cited

### ISSUE THREAD

**Issue by jhpoelen** [osmose-model/osmose-web-api#186]
Currently, the osmose-web-api uses fishbase/sealifebase archives made available at https://github.com/jhpoelen/fishbase_archiver . In order to make these archives citable in our upcoming paper, I would suggest to take the following steps.

Suggested steps:

0. create a new repository called "fishbase-archive" or "fishbase-sealifebase-archive". If there's no organization associated with fishbase/sealifebase on github, I'd suggest to create one.
1. add a short description for the repository. 
2. add a README.md with a description of what the archives contain and how they are produced (e.g., using fishbase_archiver)
3. add a LICENSE file . Many organization now use [CC0](https://creativecommons.org/choose/zero/) while others use [CC-BY](https://creativecommons.org/licenses/by/4.0/) or [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) . 
4. enable the Zenodo-GitHub integration for the repository
5. for each *existing* releases on https://github.com/jhpoelen/fishbase_archiver, download the files and README, commit the files to the new repository and create a release. So, this would be 
6. (optional) After creating each (patch) release, add the DOIs to the pre-existing releases on fishbase_archiver to indicate that a permanent record of the archives exist elsewhere.   
7. after all the releases have been published to Zenodo, share the DOI with Arnaud so that the archives can be cited.

**Comment by FIN-casey** [comment]
Hello @jhpoelen,
CC: @FIN-JBarile 

I would like to clarify step 6. Based on our understanding, we need integrate the fishbase_archiver to Zenodo then add somewhere on the Readme file the DOI for it together with the DOI of the current repository of the archiver. If that is what you expect, I cannot integrate it to Zenodo because I don't have enough access credentials. If not, kindly clarify it. Also, kindly check if what I did will suffice the need for the new repository. Thanks!

Hello @agruss2,

Sharing with you the DOI for the new fishbase-sealifebase-archiver DOI. 
[![DOI](https://zenodo.org/badge/148454670.svg)](https://zenodo.org/badge/latestdoi/148454670)

**Comment by jhpoelen** [comment]
Hi @FIN-casey  -
I've seen that you've copied over the artifacts from the github releases on https://github.com/osmose-model/fishbase-sealifebase-archiver. As you probably noticed, Zenodo does not archive binaries attached to a release. Zenodo does archive files committed to the repository itself. This is why https://zenodo.org/record/1418646#.W5vESmCZ2is only contains a readme, license and the table_names.tsv . 

Suggested is to:

1. commit the binaries the repository, *not* as binaries to the release pages.
2. once the binaries for a specific release on fishbase_archiver have been commited, create a release with a description detailing how and when the files were generated and what changed. 
3. after creating the release, confirm that zenodo contains the readme, license, table_names.tsv and all associated table .

Please note that the LICENSE file is currently an MIT license, while I understand that you'd like to use some creative commons license. Creative commons licenses are often used with data.

Without completing the steps outline above, the valuable fishbase / sealifebase archives are not archived to Zenodo. 

Please let me know if you have any questions.

**Comment by jhpoelen** [comment]
Also, I would strongly suggest to claim the ```fishbase``` github organization and create the archives in there. The archives are not specific to osmose and by making them part of the fishbase organization would emphasize this.

**Comment by QQ-Sortiz** [comment]
Hello @jhpoelen,
CC:@Dengaloo @FIN-JBarile

I added a new folder tables on the github repository so that the data files can now be included when cited to Zenodo. Thanks!

**Comment by FIN-JBarile** [comment]
Hi, 

Please see [https://github.com/FiN-FBSLB/fishbase-sealifebase-archive](https://github.com/FiN-FBSLB/fishbase-sealifebase-archive)

@agruss2

**Comment by jhpoelen** [comment]
This looks great! 

Minor comment is to to add a LICENSE file with the CC-BY-NC terms (see https://github.com/FiN-FBSLB/fishbase-sealifebase-archive/issues/1) . This way, github and others can easily be made a aware of the license.

**Comment by agruss2** [comment]
@QQ-Sortiz (CC: @FIN-JBarile @jhpoelen )
I am closing this issue, since the only comment that remains to be addressed can also be found here: FiN-FBSLB/fishbase-sealifebase-archive#1 
Many thanks for everything!
