### ISSUE TITLE
fishbase popqb and estimate tables no longer exist - suggest to update fishbase-mapping.csv

### ISSUE THREAD

**Issue by jhpoelen** [osmose-model/osmose-web-api#187]
During routine maintenance, I noticed that the estimate and popqb tables no longer exist. This was also supported by a visit to https://fishbaseapi.readme.io/docs/ - the documentation did not mention either popqb and estimate tables. 

@agruss2 @Dengaloo @sckott Was the removal of the estimate and popqb table done on purpose?

--- from logging 2019-05-23
[https://fishbase.ropensci.org/estimate?SpecCode=120&limit=5000] processing... completed with code [400].
[https://fishbase.ropensci.org/popqb?SpecCode=120&limit=5000] processing... completed with code [400].

**Comment by jhpoelen** [comment]
It appears that the estimate table was removed in v7 (aka 2019-02-01). I've pegged the osmose api to use v6 for now.

**Comment by sckott** [comment]
not sure what happened, will be rolling out a new version to the API next monday, it may be back, can't look at it right now though

**Comment by FIN-JBarile** [comment]
The estimate and popqb tables should still be included in the database.  Will check from our end as well. Thanks for alert.

**Comment by jhpoelen** [comment]
@sckott @FIN-JBarile thanks for your replies. Please communicate how things settle, so I can make appropriate changes. I am pleased to see that our continued integration help detect (and hopefully resolve) unexpected issues.

**Comment by jhpoelen** [comment]
Looks like the current version 2019-04-01 has re-included the ```estimate``` and ```popqb``` tables :

```
$ curl -L https://fishbase.ropensci.org/estimate | jq . | head 
{
  "count": 34299,
  "returned": 10,
  "data": [
    {
      "SpecCode": 2,
      "MaxLengthTL": 73.2,
      "TLObserved": "\u0001",
      "Troph": 2,
      "seTroph": 0,
...
```
and 
```
$ curl -L https://fishbase.ropensci.org/popqb | jq . | head 
{
  "count": 162,
  "returned": 10,
  "data": [
    {
      "AutoCtr": 1,
      "StockCode": 1,
      "SpecCode": 2,
      "PopQBRefNo": 2939,
      "PopQB": 2.2100000381469727,
```

Thanks for your patience.
